using System.Globalization;
using System.Text;

namespace PowerLinq.DaxConverter.Model;

/// <summary>
/// Generates the C# contracts from the model's schema.
/// </summary>
/// <remarks>
/// <para>
/// <b>It eliminates a class of error instead of detecting it.</b> Table, column and measure names
/// come from the model, so diverging stops being possible: there is no claim left to check. That is
/// why the choice was generation rather than validation at run time — and
/// <see cref="DaxContractValidator"/> still exists as a safety net for hand-written contracts and
/// for a model that changes after generation.
/// </para>
/// <para>
/// <b>It emits text, not a file.</b> Where to write is decided by the calling tool — and that is
/// what makes generation testable without touching disk.
/// </para>
/// <para>
/// <b>Measures come out as constants.</b> That is what closes the "a non-existent measure name is
/// detected" criterion, and it closes it better than a check would: reflection cannot reach a
/// measure name, because it is an argument of <c>MeasureAsync</c> written at the call site. With a
/// generated constant, a typo becomes a <b>compile</b> error.
/// </para>
/// </remarks>
public static class DaxContractGenerator
{
    /// <summary>Generates the contracts file.</summary>
    /// <param name="schema">The model's schema.</param>
    /// <param name="namespaceName">The namespace of the generated types.</param>
    /// <remarks>
    /// One file, not one per table: the natural consumer is a build target that writes the whole
    /// output, and one file per table would turn a table removed from the model into an orphan file
    /// that keeps compiling.
    /// </remarks>
    public static string Generate(DaxModelSchema schema, string namespaceName)
    {
        ArgumentNullException.ThrowIfNull(schema);
        ArgumentException.ThrowIfNullOrWhiteSpace(namespaceName);

        var writer = new StringBuilder();

        writer.AppendLine("// <auto-generated />")
              .AppendLine("// Gerado a partir do esquema do modelo semântico. Não edite: a próxima")
              .AppendLine("// geração sobrescreve. Para mudar o contrato, mude o modelo.")
              .AppendLine("#nullable enable")
              .AppendLine()
              // System always goes in: DateTime? shows up in any model with a date column, and the
              // generated code may land in a project without ImplicitUsings. Emitting it
              // conditionally would buy one using fewer and one compile error more.
              .AppendLine("using System;")
              .AppendLine("using PowerLinq.DaxConverter.Attributes;")
              .AppendLine()
              .AppendLine(CultureInfo.InvariantCulture, $"namespace {namespaceName};");

        foreach (DaxSchemaTable table in schema.Tables.OrderBy(t => t.Name, StringComparer.Ordinal))
            AppendTable(writer, table);

        AppendMeasures(writer, schema);

        return writer.ToString();
    }

    private static void AppendTable(StringBuilder writer, DaxSchemaTable table)
    {
        string typeName = Identifier(table.Name);

        writer.AppendLine()
              .AppendLine(CultureInfo.InvariantCulture, $"/// <summary>A tabela <c>{table.Name}</c> do modelo.</summary>")
              .AppendLine(CultureInfo.InvariantCulture, $"[DaxTable({Quote(table.Name)})]")
              .AppendLine(CultureInfo.InvariantCulture, $"public sealed class {typeName}")
              .AppendLine("{");

        bool first = true;

        // A repeated property name is possible: two columns whose names differ only by a character
        // the identifier drops — "Valor R$" and "Valor (R$)" — would collide. The suffix keeps
        // both, because silently dropping one would lose a column of the model.
        var used = new HashSet<string>(StringComparer.Ordinal) { typeName };

        foreach (DaxSchemaColumn column in table.Columns)
        {
            if (!first)
                writer.AppendLine();

            first = false;

            writer.AppendLine(CultureInfo.InvariantCulture, $"    [DaxColumn({Quote($"{Reference(table.Name)}[{column.Name}]")})]")
                  .AppendLine(CultureInfo.InvariantCulture, $"    public {ClrType(column.DataType)} {Unique(used, Identifier(column.Name))} {{ get; set; }}{Initializer(column.DataType)}");
        }

        writer.AppendLine("}");
    }

    private static void AppendMeasures(StringBuilder writer, DaxModelSchema schema)
    {
        List<DaxSchemaMeasure> measures =
            [.. schema.Measures.OrderBy(m => m.Name, StringComparer.Ordinal)];

        if (measures.Count == 0)
            return;

        writer.AppendLine()
              .AppendLine("/// <summary>Os nomes das medidas do modelo.</summary>")
              .AppendLine("/// <remarks>")
              .AppendLine("/// Constantes, e não texto no ponto da chamada: com elas o erro de digitação num nome de")
              .AppendLine("/// medida passa a ser erro de compilação, que é onde ele deveria morrer.")
              .AppendLine("/// </remarks>")
              .AppendLine("public static class Measures")
              .AppendLine("{");

        var used = new HashSet<string>(StringComparer.Ordinal) { "Measures" };
        bool first = true;

        foreach (DaxSchemaMeasure measure in measures)
        {
            if (!first)
                writer.AppendLine();

            first = false;

            writer.AppendLine(CultureInfo.InvariantCulture, $"    /// <summary>A medida <c>[{measure.Name}]</c>, de <c>{measure.Table}</c>.</summary>")
                  .AppendLine(CultureInfo.InvariantCulture, $"    public const string {Unique(used, Identifier(measure.Name))} = {Quote(measure.Name)};");
        }

        writer.AppendLine("}");
    }

    /// <summary>
    /// The table reference as DAX writes it: in single quotes when the name is not a simple
    /// identifier.
    /// </summary>
    private static string Reference(string table) =>
        table.All(c => char.IsLetterOrDigit(c) || c == '_')
            ? table
            : $"'{table}'";

    /// <summary>A C# identifier from a model name.</summary>
    /// <remarks>
    /// A model name is free-form — it may contain spaces, accents, symbols. Anything that is not a
    /// letter or a digit becomes a word boundary, and each word's initial is raised:
    /// <c>VL_REALIZADO_BRL</c> becomes <c>VlRealizadoBrl</c>. Accents are <b>preserved</b>, because
    /// C# accepts them and transliterating would change the name that whoever reads the model
    /// recognizes.
    /// </remarks>
    private static string Identifier(string name)
    {
        var identifier = new StringBuilder(name.Length);
        bool upperNext = true;

        foreach (char c in name)
        {
            if (!char.IsLetterOrDigit(c))
            {
                upperNext = true;
                continue;
            }

            identifier.Append(upperNext ? char.ToUpperInvariant(c) : char.ToLowerInvariant(c));
            upperNext = false;
        }

        if (identifier.Length == 0)
            return "Column";

        // An identifier cannot start with a digit, and a column name can — "2024" is a valid column
        // name in a calendar model.
        if (char.IsDigit(identifier[0]))
            identifier.Insert(0, '_');

        return identifier.ToString();
    }

    private static string Unique(HashSet<string> used, string candidate)
    {
        if (used.Add(candidate))
            return candidate;

        for (int suffix = 2; ; suffix++)
        {
            string attempt = $"{candidate}{suffix.ToString(CultureInfo.InvariantCulture)}";

            if (used.Add(attempt))
                return attempt;
        }
    }

    /// <remarks>
    /// Everything nullable except <c>string</c>, which gets an initializer. That is deliberate: in
    /// DAX every column can return <c>BLANK</c>, and a non-nullable <c>decimal</c> would erase the
    /// difference between "summed to zero" and "there was no row" — the same decision
    /// <c>MinAsync</c> and <c>MeasureAsync</c> already make.
    /// </remarks>
    private static string ClrType(string dataType) => dataType switch
    {
        "String" => "string",
        "Int64" => "long?",
        "Double" => "double?",
        "Decimal" => "decimal?",
        "DateTime" => "DateTime?",
        "Boolean" => "bool?",

        // Binary and Variant have no CLR type materialization knows how to convert, and Unknown is
        // the code the read did not recognize. `string` is what the server delivers in all three,
        // and it is what the type table accepts.
        _ => "string",
    };

    private static string Initializer(string dataType) =>
        ClrType(dataType) == "string" ? " = \"\";" : "";

    private static string Quote(string value) =>
        $"\"{value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal)}\"";
}
